# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7988866a747897ccec0d86c48c285c91684ec6afc221b06f3bd83b10fb53a30bb2a2224230692913454af7523b3ffa20bf480f95b7ae079a3cf913f6d099e8d8

test:
  secret_key_base: 0d06a9a13cfb1648c38732be3aa36d896e306e6f48be4b83bb714ac8d1365c500eb6353b4dfff28e838771c980cf61f81c4eb14fab8aef0809749d195a5d9fe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
